Traceback (most recent call last):
  File "server.py", line 14, in <module>
    with open(flagfile) as f:
IOError: [Errno 2] No such file or directory: 'flag'
2017/08/03 16:46:48 socat[26245] E write(5, 0x1ebe410, 2): Broken pipe
2017/08/03 16:51:05 socat[26539] E write(6, 0x1ebe410, 128): Broken pipe
2017/08/03 16:56:09 socat[27368] E write(5, 0x1ebe410, 2): Broken pipe
2017/08/03 16:59:41 socat[27584] E write(5, 0x1ebe410, 4): Broken pipe
2017/08/03 17:11:40 socat[28834] E write(6, 0x1ebe410, 146): Broken pipe
2017/08/03 17:12:45 socat[28933] E write(6, 0x1ebe410, 18): Broken pipe
2017/08/03 17:13:14 socat[29034] E write(6, 0x1ebe410, 127): Broken pipe
